### PR TITLE
Add flannel-s390x to resources

### PR DESCRIPTION
**Pull request by battlemidget**
Need this defined so we can upload flannel s390 resources in CI

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

### CODE REVIEW

**Comment by Cynerva** [comment]
Someone might look at this and say "hey, canal works on s390x" when it really doesn't because there's no calico-s390x resource. I don't think we should add flannel-s390x to the charm until we can add calico-s390x also.

**Comment by battlemidget** [comment]
I'm just going on what resources get built, i assumed if we built them it was part of a working charm. Can the script then be updated to not include s390x until calico is available?

**Comment by Cynerva** [comment]
Sure, here you go: https://github.com/juju-solutions/layer-canal/pull/29

**Comment by battlemidget** [comment]
Closing this per review

**Pull request closed without merging**
