### PR TITLE
stub out charm-pre-install to skip docker-compose setup to facilitate…

### PR DESCRIPTION
**Pull request by wwwtyro**
… offline installation

Probably fine to merge, but I'm still testing.

### CODE REVIEW

**Comment by marcoceppi** [comment]
Is layer:docker even needed? I only see it being leveraged in one location `docker.available` as a gate. Seems we could just drop that layer all together?

**Comment by wwwtyro** [comment]
Thanks for taking a look! We do need docker installed: https://github.com/juju-solutions/layer-canal/blob/master/templates/calico-node.service#L10

**Comment by marcoceppi** [comment]
Thanks for clearing that up, perhaps there is a better long term solution
for this. Otherwise this looks fine

**Comment by wwwtyro** [comment]
Sibling PR: https://github.com/juju-solutions/layer-calico/pull/15

**Pull request merged**
